name: Build and Release SunnyOS ISOs
on:
  workflow_dispatch:
    inputs:
      release_title:
        description: 'Release Title'
        required: true
      description:
        description: 'Release Description'
        required: true
      release_version:
        description: 'Release Version Tag'
        required: true
jobs:
  build-gnome:
    name: Build Gnome ISO
    uses: ./.github/workflows/reusable_build_iso.yml
    with:
      branch: sunnyos_gnome
  build-feather-gnome:
    name: Build Feather Gnome ISO
    uses: ./.github/workflows/reusable_build_iso.yml
    with:
      branch: lite_gnome
  build-budgie:
    name: Build Budgie ISO
    uses: ./.github/workflows/reusable_build_iso.yml
    with:
      branch: sunnyos_budgie
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs:
      - build-gnome
      - build-feather-gnome
      - build-budgie
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.release_title }}
          body: ${{ inputs.description }}
          tag_name: ${{ inputs.release_version }}
          prerelease: true
